In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('precision', 4)

In [2]:
cdc = pd.read_csv("2020-08-24-all-forecasted-cases-model-data.csv")
cdc.info()
cdc.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206173 entries, 0 to 206172
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   model            206173 non-null  object
 1   forecast_date    206173 non-null  object
 2   target           206173 non-null  object
 3   target_end_date  206173 non-null  object
 4   location_name    206173 non-null  object
 5   State            206173 non-null  object
 6   fips             206173 non-null  object
 7   point            206173 non-null  int64
 8   quantile_0.025   172701 non-null  float64
 9   quantile_0.25    172701 non-null  float64
 10  quantile_0.75    172701 non-null  float64
 11  quantile_0.975   172537 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 18.9+ MB

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Karlen,2020-08-24,1 wk ahead inc case,2020-08-29,Alabama,Alabama,01,6064,3587.0,4657.0,7436.0,10082.0
1,IQVIA,2020-08-24,1 wk ahead inc case,2020-08-29,Alabama,Alabama,01,8401,NaN,NaN,NaN,NaN
2,Columbia,2020-08-24,1 wk ahead inc case,2020-08-29,Alabama,Alabama,01,5340,4153.0,4830.0,5977.0,8053.0
3,ESG,2020-08-24,1 wk ahead inc case,2020-08-29,Alabama,Alabama,01,3966,3722.0,3882.0,4050.0,4209.0
4,UGA-CEID,2020-08-24,1 wk ahead inc case,2020-08-29,Alabama,Alabama,01,6735,4286.0,5884.0,7668.0,9085.0

Strategy:
* Group by state and aggregate mean for continuous values (predictions)
* use the actual weekly case increase data (load from another source) as y
* use the errors, y - yhat, to measure how close or far the predictions were
* then implement the weights to train a model to approximate future cases